// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/redisoo.proto

package redisoo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetStringResponse_Status int32

const (
	GetStringResponse_STATUS_UNKNOWN   GetStringResponse_Status = 0
	GetStringResponse_STATUS_NOT_FOUND GetStringResponse_Status = 1
	GetStringResponse_STATUS_INSERT    GetStringResponse_Status = 2
	GetStringResponse_STATUS_REPLACE   GetStringResponse_Status = 3
	GetStringResponse_STATUS_APPEND    GetStringResponse_Status = 4
)

var GetStringResponse_Status_name = map[int32]string{
	0: "STATUS_UNKNOWN",
	1: "STATUS_NOT_FOUND",
	2: "STATUS_INSERT",
	3: "STATUS_REPLACE",
	4: "STATUS_APPEND",
}

var GetStringResponse_Status_value = map[string]int32{
	"STATUS_UNKNOWN":   0,
	"STATUS_NOT_FOUND": 1,
	"STATUS_INSERT":    2,
	"STATUS_REPLACE":   3,
	"STATUS_APPEND":    4,
}

func (x GetStringResponse_Status) String() string {
	return proto.EnumName(GetStringResponse_Status_name, int32(x))
}

func (GetStringResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d41aa9e5425d0f2, []int{1, 0}
}

type GetStringRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStringRequest) Reset()         { *m = GetStringRequest{} }
func (m *GetStringRequest) String() string { return proto.CompactTextString(m) }
func (*GetStringRequest) ProtoMessage()    {}
func (*GetStringRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d41aa9e5425d0f2, []int{0}
}

func (m *GetStringRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStringRequest.Unmarshal(m, b)
}
func (m *GetStringRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStringRequest.Marshal(b, m, deterministic)
}
func (m *GetStringRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStringRequest.Merge(m, src)
}
func (m *GetStringRequest) XXX_Size() int {
	return xxx_messageInfo_GetStringRequest.Size(m)
}
func (m *GetStringRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStringRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStringRequest proto.InternalMessageInfo

func (m *GetStringRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetStringResponse struct {
	Status               GetStringResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=redisoo.GetStringResponse_Status" json:"status,omitempty"`
	Value                []byte                   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlMs                uint32                   `protobuf:"varint,3,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetStringResponse) Reset()         { *m = GetStringResponse{} }
func (m *GetStringResponse) String() string { return proto.CompactTextString(m) }
func (*GetStringResponse) ProtoMessage()    {}
func (*GetStringResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d41aa9e5425d0f2, []int{1}
}

func (m *GetStringResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStringResponse.Unmarshal(m, b)
}
func (m *GetStringResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStringResponse.Marshal(b, m, deterministic)
}
func (m *GetStringResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStringResponse.Merge(m, src)
}
func (m *GetStringResponse) XXX_Size() int {
	return xxx_messageInfo_GetStringResponse.Size(m)
}
func (m *GetStringResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStringResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStringResponse proto.InternalMessageInfo

func (m *GetStringResponse) GetStatus() GetStringResponse_Status {
	if m != nil {
		return m.Status
	}
	return GetStringResponse_STATUS_UNKNOWN
}

func (m *GetStringResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetStringResponse) GetTtlMs() uint32 {
	if m != nil {
		return m.TtlMs
	}
	return 0
}

func init() {
	proto.RegisterEnum("redisoo.GetStringResponse_Status", GetStringResponse_Status_name, GetStringResponse_Status_value)
	proto.RegisterType((*GetStringRequest)(nil), "redisoo.GetStringRequest")
	proto.RegisterType((*GetStringResponse)(nil), "redisoo.GetStringResponse")
}

func init() {
	proto.RegisterFile("proto/redisoo.proto", fileDescriptor_2d41aa9e5425d0f2)
}

var fileDescriptor_2d41aa9e5425d0f2 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0xc6, 0xa6, 0x38, 0xd8, 0xb2, 0x1d, 0x2b, 0xc4, 0x9e, 0x6a, 0xf0, 0xd0, 0x53,
	0x84, 0x7a, 0xf2, 0x18, 0x4c, 0x14, 0x51, 0x37, 0x61, 0x93, 0xe0, 0x31, 0x54, 0x5c, 0xa4, 0x18,
	0xbb, 0x35, 0x3b, 0x11, 0x7c, 0x64, 0xdf, 0x42, 0xdc, 0x44, 0x09, 0x68, 0x6f, 0xf3, 0x0f, 0xdf,
	0xcf, 0xf0, 0x0d, 0x1c, 0x6e, 0x2b, 0x45, 0xea, 0xac, 0x92, 0x4f, 0x6b, 0xad, 0x94, 0x6f, 0x12,
	0x0e, 0xdb, 0xe8, 0x9d, 0x02, 0xbb, 0x96, 0x94, 0x52, 0xb5, 0xde, 0x3c, 0x0b, 0xf9, 0x56, 0x4b,
	0x4d, 0xc8, 0xc0, 0x7e, 0x91, 0x1f, 0xae, 0x35, 0xb7, 0x16, 0x07, 0xe2, 0x7b, 0xf4, 0x3e, 0x2d,
	0x98, 0x74, 0x30, 0xbd, 0x55, 0x1b, 0x2d, 0xf1, 0x02, 0x1c, 0x4d, 0x2b, 0xaa, 0xb5, 0x41, 0xc7,
	0xcb, 0x13, 0xff, 0xe7, 0xc8, 0x1f, 0xd6, 0x4f, 0x0d, 0x28, 0xda, 0x02, 0x4e, 0x61, 0xf0, 0xbe,
	0x2a, 0x6b, 0xe9, 0xf6, 0xcd, 0x91, 0x26, 0xe0, 0x11, 0x38, 0x44, 0x65, 0xf1, 0xaa, 0x5d, 0x7b,
	0x6e, 0x2d, 0x46, 0x62, 0x40, 0x54, 0xde, 0x6b, 0xaf, 0x04, 0xa7, 0xa9, 0x23, 0xc2, 0x38, 0xcd,
	0x82, 0x2c, 0x4f, 0x8b, 0x9c, 0xdf, 0xf2, 0xf8, 0x81, 0xb3, 0x1e, 0x4e, 0x81, 0xb5, 0x3b, 0x1e,
	0x67, 0xc5, 0x55, 0x9c, 0xf3, 0x90, 0x59, 0x38, 0x81, 0x51, 0xbb, 0xbd, 0xe1, 0x69, 0x24, 0x32,
	0xd6, 0xef, 0x94, 0x45, 0x94, 0xdc, 0x05, 0x97, 0x11, 0xb3, 0x3b, 0x58, 0x90, 0x24, 0x11, 0x0f,
	0xd9, 0xde, 0x32, 0x86, 0xa1, 0x68, 0x34, 0x30, 0x84, 0xfd, 0x5f, 0x13, 0x3c, 0xfe, 0xcf, 0xce,
	0x3c, 0x6c, 0x36, 0xdb, 0x2d, 0xee, 0xf5, 0x1e, 0x1d, 0xf3, 0xf2, 0xf3, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xa4, 0x27, 0x04, 0x74, 0x89, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RedisooClient is the client API for Redisoo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RedisooClient interface {
	GetString(ctx context.Context, in *GetStringRequest, opts ...grpc.CallOption) (*GetStringResponse, error)
}

type redisooClient struct {
	cc grpc.ClientConnInterface
}

func NewRedisooClient(cc grpc.ClientConnInterface) RedisooClient {
	return &redisooClient{cc}
}

func (c *redisooClient) GetString(ctx context.Context, in *GetStringRequest, opts ...grpc.CallOption) (*GetStringResponse, error) {
	out := new(GetStringResponse)
	err := c.cc.Invoke(ctx, "/redisoo.Redisoo/GetString", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedisooServer is the server API for Redisoo service.
type RedisooServer interface {
	GetString(context.Context, *GetStringRequest) (*GetStringResponse, error)
}

// UnimplementedRedisooServer can be embedded to have forward compatible implementations.
type UnimplementedRedisooServer struct {
}

func (*UnimplementedRedisooServer) GetString(ctx context.Context, req *GetStringRequest) (*GetStringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetString not implemented")
}

func RegisterRedisooServer(s *grpc.Server, srv RedisooServer) {
	s.RegisterService(&_Redisoo_serviceDesc, srv)
}

func _Redisoo_GetString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisooServer).GetString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/redisoo.Redisoo/GetString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisooServer).GetString(ctx, req.(*GetStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Redisoo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "redisoo.Redisoo",
	HandlerType: (*RedisooServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetString",
			Handler:    _Redisoo_GetString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/redisoo.proto",
}
